

# 2025 publications

- id: pubmed:39910058
  highlight: true
  image: images/publications/pubmed_39910058.png
  buttons:
    - type: website
      link: https://orca.zhoulab.io/
  tags:
    - Gene regulation
    - Gene silencing
    - Medical genomics

- id: pubmed:40933505
  title: "Clinical Practice Guidelines for the Diagnosis, Management, and Surveillance of LMNB1-Related Autosomal Dominant Leukodystrophy"
  image: images/publications/pubmed_40933505.png
  tags:
    - Cognitive Disorders/Dementia
    - Genetics
    - Leukodystrophies
    - MRI

- id: pubmed:40025114
  title: Clinical Practice Guidelines for the Diagnosis, Management, and Surveillance of LMNB1-Related Autosomal Dominant Leukodystrophy
  image: images/publications/pubmed_40025114.png
  tags:
    - Lamin B1
    - Laminopathies
    - Autosomal dominant leukodystrophy
    - High-content screening

# 2024 publications

- id: pubmed:39292993
  highlight: true
  image: images/publications/pubmed_39292993.png
  tags:
    - 4.1B
    - neurodevelopmental disorder
    - loss-of-function
    - delayed myelination
    - oligodendroglia

# 2023 publications

- id: pubmed:37609196
  image: images/publications/pubmed_37609196.png
  tags:
    - Genetics

- id: pubmed:37542275
  image: images/publications/pubmed_37542275.png
  tags:
    - Oligodendrocyte
    - Cell culture
    - Myelin
    - Oli-neu

- id: pubmed:37450245
  image: images/publications/pubmed_37450245.png
  tags:
    - ADLD
    - Cellular Morphology
    - Cellular Signaling
    - Demyelination
    - Lamin B1
    - Neurodegenerative Diseases
    - Rare Diseases

# 2022 publications

- id: pubmed:35953447
  highlight: true
  image: images/publications/pubmed_35953447.png
  tags:
    - hypomyelinating leukodystrophies
    - TMEM163
    - genomic testing
    - oligodendrocytes

- id: pubmed:35488860
  highlight: true
  image: images/publications/pubmed_35488860.png
  tags:
    - alternative polyadenylation
    - cell-type–specific regulation
    - confounding factors
    - post-transcriptional regulation
    - single-cell RNA

# 2021 publications

- id: pubmed:34447008
  title: "LMNB1 Duplication-Mediated Autosomal Dominant Adult-Onset Leukodystrophy in an Indian Family"
  image: images/publications/pubmed_34447008.png
  tags:
    - ADLD
    - LMNB1
    - adult-onset leukodystrophy
    - autonomic dysfunction
    - lamin B

- id: pubmed:33666368
  image: images/publications/pubmed_33666368.png
  tags:
    - NKX2-1
    - benign hereditary chorea
    - chromosome 14q13.2-q13.3
    - copy number variations
    - non-coding regulatory elements

# 2020 publications

- id: pubmed:32913013
  title: "Cardiac phenotype in ATP1A3-related syndromes: A multicenter cohort study"
  image: images/publications/pubmed_32913013.png
  tags:
    - Cardiac
    - Cerebrovascular Disease/Stroke
    - Epilepsy/Seizures
    - Genetics
    - Movement Disorders

- id: pubmed:32463361
  title: "TUBB4A mutations result in both glial and neuronal degeneration in an H-ABC leukodystrophy mouse model"
  image: images/publications/pubmed_32463361.png
  tags:
    - TUBB4A
    - hypomyelination
    - leukodystrophy
    - microtubule
    - mouse
    - neurodegeneration
    - neuroscience

- id: pubmed:32349647
  image: images/publications/pubmed_32349647.png
  tags:
    - autosomal dominant leukodystrophy
    - high-content analysis
    - high-throughput screening
    - lamin B1
    - multivariate analysis

- id: pubmed:32187401
  image: images/publications/pubmed_32187401.png
  tags:
    - Akt
    - FTLD
    - Fus
    - cholesterol
    - hyperactivity
    - myelin

# 2019 publications

- id: pubmed:30949481
  image: images/publications/pubmed_30949481.png
  tags:
    - chromatin
    - lamin B1
    - leukodystrophy
    - lipid synthesis
    - myelin
    - nuclear lamina
    - nuclear structure

- id: pubmed:30765529
  highlight: true
  image: images/publications/pubmed_30765529.png
  tags:
    - nucleus
    - lamin
    - bleb
    - curvature
    - meshwork

- id: pubmed:30842973
  image: images/publications/pubmed_30842973.png
  tags:
    - Autonomic Diseases
    - Clinical Neurology
    - Demyelinating Disease (CNS)
    - Genetics
    - Imaging
    - MRI

# 2018 publications

- id: pubmed:30014503
  image: images/publications/pubmed_30014503.png
 
# 2017 publications

- id: pubmed:29262292
  image: images/publications/pubmed_29262292.png
  tags:
    - Arterial pressure
    - Breathing
    - Gait
    - Heart rate
    - Lamin
    - Leukodystrophy
    - Mice
    - Oligodendrocyte
    - Sleep
    - Sympathetic

- id: pubmed:28973395
  image: images/publications/pubmed_28973395.png
  tags:
    - phenotype
    - mutation
    - microtubules
    - oligodendroglia
    - tubulin
    - cerebellum
    - myelin
    - hypomyelination
    - polymerization

# 2016 publications

- id: pubmed:27854160
  image: images/publications/pubmed_27854160.png
  tags:
    - ADLD demyelination
    - Lamin B1
    - epigenetic modifications
    - leukodystrophy
    - lipid synthesis
    - nuclear lamina
    - nuclear structure
    - transcription

# 2015 publications

- id: pubmed:26453127
  tags:
    - ATP1A3 gene
    - Ataxia
    - Cerebellum
    - Channelopathies
    - Episodic encephalopathy
    - Fever
    - Migraine

- id: pubmed:26311780
  highlight: true
  image: images/publications/pubmed_26311780.png
  tags:
    - chromatin
    - demyelination
    - gene expression
    - inflammation
    - Lamin B1
    - lipid

- id: pubmed:25927548
  image: images/publications/pubmed_25927548.png
  tags:
    - ATP1A3 gene
    - Ataxia
    - Cerebellum
    - Channelopathies
    - Episodic encephalopathy
    - Fever
    - Migraine

# 2014 publications

- id: pubmed:25359263
  image: images/publications/pubmed_25359263.png
 
- id: pubmed:25339210
  image: images/publications/pubmed_25339210.png
  tags:
    - Cerebellum
    - Gait disorders/Ataxia
    - Genetics
    - Imaging
    - Movement Disorders
    - MRI

- id: pubmed:25085639
  image: images/publications/pubmed_25085639.png
  tags:
    - Genetic linkage
    - Genetics
    - Leukodystrophies
    - Medical/Systemic Disease
    - Pediatric

# 2013 publications

- id: pubmed:23649844
  highlight: true
  image: images/publications/pubmed_23649844.png
  tags:
    - Lamin B1
    - leukodystrophy
    - ADLD
    - duplication Alu
    - NHEJ
    - FoSTeS
    - MMBIR

- id: pubmed:23676464
  image: images/publications/pubmed_23676464.png
  
# 2010 publications

- id: pubmed:20816241

# 2006 publications

- id: pubmed:16951681
  highlight: true
  image: images/publications/pubmed_16951681.png
  
# 2005 publications

- id: pubmed:15800623
  highlight: true
  image: images/publications/pubmed_15800623.png

- id: pubmed:15457499
  tags:
    - Machado Joseph Disease/spinocerebellar ataxia 3
    - CAG repeat
    - repeat instability
    - haplotype
    - intermediate allele

#- id: 
#  type: paper
#  description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
#  date: 2020-12-4
#  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
#  buttons:
#    - type: manubot
#      link: https://greenelab.github.io/meta-review/
#    - type: source
#      text: Manuscript Source
#      link: https://github.com/greenelab/meta-review
#    - type: website
#      link: http://manubot.org/
#  tags:
#    - open science
#    - collaboration
#  repo: greenelab/meta-review

#- id: doi:10.1016/j.csbj.2020.05.017
#  image: https://ars.els-cdn.com/content/image/1-s2.0-S2001037020302804-gr1.jpg

#- id: doi:10.7554/eLife.32822
#  image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp
